
name: Release Creation
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Insert release values into system.json
      - name: Insert release-specific values in manifest file
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "system.json"
        env:
          version: ${{github.event.release.tag_name}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/dragonslayer.zip

      # Create signature.json
      - name: Create signature.json
        run: |
          echo '{
            "id": "dragonslayer",
            "version": "'${{github.event.release.tag_name}}'",
            "signature": "",
            "protected": false
          }' > signature.json

      # Create zip file with all required files
      - name: Create zip file
        run: |
          ls -la
          zip -r ./dragonslayer.zip system.json template.json package.json module/dragonslayer.mjs styles/dragonslayer.css lang/en.json

      # Update release with files
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./dragonslayer.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
