name: Release Creation
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip file
        run: zip -r ./dragonslayer.zip system.json template.json scripts/ templates/ styles/

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./dragonslayer.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
